name: Deploy to Cloudflare

on:
  push:
    branches: [main]

jobs:
  migrate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run migrations
        working-directory: ./apps/api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bun db:migrate:prod
        
      - name: Deploy API to Workers
        working-directory: ./apps/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bun deploy
        
      - name: Build frontend
        working-directory: ./apps/web
        run: bun run build
        
      - name: Deploy frontend to Pages
        working-directory: ./apps/web
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bunx wrangler pages deploy --project-name=better-hono-react-web